#import "lyrics_layer.h"
#import <AppKit/AppKit.h>
#include <assert.h>
static void values(NSArray*a,double*out,size_t n){assert(a.count==n);for(size_t i=0;i<n;i++)out[i]=[a[i] doubleValue];}
int main(int argc,const char**argv){@autoreleasepool{
    assert(argc==2||argc==3);NSData*d=[NSData dataWithContentsOfFile:[NSString stringWithUTF8String:argv[1]]];assert(d);NSDictionary*f=[NSJSONSerialization JSONObjectWithData:d options:0 error:nil];assert(f);
    [NSApplication sharedApplication];double logicalW=[f[@"width"] doubleValue],logicalH=[f[@"height"] doubleValue],scale=[f[@"scale"] doubleValue];
    NSWindow*w=[[NSWindow alloc]initWithContentRect:NSMakeRect(0,0,logicalW,logicalH) styleMask:NSWindowStyleMaskBorderless backing:NSBackingStoreBuffered defer:NO];NSView*scene=[[NSView alloc]initWithFrame:w.contentView.bounds];[w.contentView addSubview:scene];NSView*gpui=[[NSView alloc]initWithFrame:w.contentView.bounds];[w.contentView addSubview:gpui];void*c=gmgn_lyrics_layer_create((__bridge void*)gpui);assert(c);assert(gmgn_lyrics_layer_capture(c,1));
    for(NSDictionary*a in f[@"atlases"]){NSData*p=[[NSData alloc]initWithBase64EncodedString:a[@"rgba"] options:0];assert(p);assert(gmgn_lyrics_layer_atlas(c,[a[@"id"] unsignedLongLongValue],[a[@"width"] unsignedIntValue],[a[@"height"] unsignedIntValue],p.bytes,p.length));}
    NSArray*input=f[@"batches"];size_t depths[256]={0},existingDepth=0;assert(input.count<=256);for(NSUInteger i=0;i<input.count;i++){id parent=input[i][@"parent"];depths[i]=parent==NSNull.null?1:depths[[parent unsignedIntegerValue]]+1;existingDepth=MAX(existingDepth,depths[i]);}size_t requested=argc==3?(size_t)atoi(argv[2]):existingDepth;assert(requested>=existingDepth&&requested<=16);size_t wrappers=requested-existingDepth,total=input.count+wrappers;GMGNLyricsBatch*b=calloc(total,sizeof(*b));for(size_t i=0;i<wrappers;i++){b[i].parent_index=(int64_t)i-1;b[i].opacity=0.99;}
    for(NSUInteger i=0;i<input.count;i++){NSDictionary*n=input[i];NSArray*glyphs=n[@"glyphs"];GMGNLyricsGlyph*g=calloc(glyphs.count,sizeof(*g));GMGNLyricsBatch*node=&b[i+wrappers];node->glyphs=g;node->count=glyphs.count;node->sigma=[n[@"sigma"] doubleValue];node->blur_mix=[n[@"blur_mix"] doubleValue];node->opacity=[n[@"opacity"] doubleValue];node->parent_index=n[@"parent"]==NSNull.null?(int64_t)wrappers-1:[n[@"parent"] longLongValue]+wrappers;values(n[@"glow"],node->glow,4);
    for(NSUInteger j=0;j<glyphs.count;j++){NSDictionary*x=glyphs[j];g[j].atlas_id=[x[@"atlas_id"] unsignedLongLongValue];g[j].width=[x[@"width"] doubleValue];g[j].height=[x[@"height"] doubleValue];values(x[@"matrix"],g[j].matrix,9);values(x[@"uv"],g[j].uv,4);values(x[@"rgba"],g[j].rgba,4);}}
    assert(gmgn_lyrics_layer_set_roi(c,0));assert(gmgn_lyrics_layer_render_frame(c,b,total,scale));uint32_t physicalW,physicalH;assert(gmgn_lyrics_layer_dimensions(c,&physicalW,&physicalH));size_t width=physicalW,height=physicalH,bytes=width*height*4;uint8_t*p=malloc(bytes),*reference=malloc(bytes);assert(gmgn_lyrics_layer_readback_presented(c,reference,bytes));
    double begin=NSProcessInfo.processInfo.systemUptime;assert(gmgn_lyrics_layer_render_frame(c,b,total,scale));assert(gmgn_lyrics_layer_readback_presented(c,reference,bytes));double baseline=(NSProcessInfo.processInfo.systemUptime-begin)*1000;
    assert(gmgn_lyrics_layer_set_roi(c,1));begin=NSProcessInfo.processInfo.systemUptime;assert(gmgn_lyrics_layer_render_frame(c,b,total,scale));assert(gmgn_lyrics_layer_readback_presented(c,p,bytes));double optimized=(NSProcessInfo.processInfo.systemUptime-begin)*1000;
    size_t transparent=0,nonzero=0,changed=0;int maxdiff=0;for(size_t i=0;i<bytes;i++){int delta=abs((int)p[i]-(int)reference[i]);maxdiff=MAX(maxdiff,delta);changed+=delta!=0;if(i%4==3){transparent+=p[i]==0;nonzero+=p[i]>0;}}assert(maxdiff<=1);assert(transparent>width*height/2&&nonzero>0);assert(p[3]==0&&p[bytes-1]==0);fprintf(stderr,"PRODUCTION_LYRICS_GPU width=%zu height=%zu batches=%zu depth=%zu transparent=%zu nonzero=%zu baseline_ms=%.2f roi_ms=%.2f max_channel_diff=%d changed_channels=%zu final_display_alpha_verified=true app_visual_acceptance=false\n",width,height,total,requested,transparent,nonzero,baseline,optimized,maxdiff,changed);free(p);free(reference);for(NSUInteger i=0;i<total;i++)free((void*)b[i].glyphs);free(b);assert(gmgn_lyrics_layer_destroy(c));
}return 0;}
