[package]
name = "gmgn-cross-platform"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
publish = false

[workspace]

[dependencies]
bevy = { version = "=0.19.1", default-features = false, features = ["std", "default_app", "3d_bevy_render", "ui_bevy_render", "scene", "default_font", "bevy_winit", "multi_threaded", "png", "x11"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
