using System;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace GMGN.UnityPlayer.World.Editor
{
    /// References runtime glTFast shaders and feature variants in Resources.
    /// These are build retention assets only; imported GLB materials keep their
    /// original textures, factors and keywords generated by glTFast.
    public sealed class WorldShaderBuild : IPreprocessBuildWithReport
    {
        public int callbackOrder => -100;
        public void OnPreprocessBuild(BuildReport report) => Prepare();

        public static void Prepare()
        {
            const string folder = "Assets/GMGN/World/Resources/WorldShaders";
            EnsureFolder("Assets/GMGN/World", "Resources");
            EnsureFolder("Assets/GMGN/World/Resources", "WorldShaders");
            var names = new[] { "glTF-pbrMetallicRoughness", "glTF-pbrSpecularGlossiness", "glTF-unlit", "glTF-pbrMetallicRoughness-Clearcoat" };
            foreach (var name in names)
            {
                var relative = name.EndsWith("-Clearcoat", StringComparison.Ordinal) ? "URP/" + name : name;
                var shader = AssetDatabase.LoadAssetAtPath<Shader>("Packages/com.unity.cloud.gltfast/Runtime/Shader/" + relative + ".shadergraph");
                if (shader == null) throw new BuildFailedException("Missing official glTFast shader graph: " + name);
                for (var features = 0; features < 4; features++)
                {
                    var path = folder + "/" + name + "-" + features + ".mat";
                    var material = AssetDatabase.LoadAssetAtPath<Material>(path);
                    if (material == null) { material = new Material(shader); AssetDatabase.CreateAsset(material, path); }
                    material.shader = shader;
                    material.shaderKeywords = Array.Empty<string>();
                    if ((features & 1) != 0) material.EnableKeyword("_OCCLUSION");
                    if ((features & 2) != 0) material.EnableKeyword("_EMISSIVE");
                    if (name == "glTF-pbrSpecularGlossiness") material.EnableKeyword("_SPECULAR_SETUP");
                    EditorUtility.SetDirty(material);
                }
            }
            AssetDatabase.SaveAssets();
            Debug.Log("[WorldShaderBuild] Retained official glTFast shader graphs and opaque occlusion/emission variants.");
        }
        static void EnsureFolder(string parent, string name)
        { if (!AssetDatabase.IsValidFolder(parent + "/" + name)) AssetDatabase.CreateFolder(parent, name); }
    }
}
