//! Native DSH ACP lifecycle + private plugin HTTP authority. No second model loop.
use crate::{
    agent_runtime_tools::{BusinessOperationResolver, HostToolTransport, LedgerHostTools},
    agent_scheduler,
    store::Database,
};
use base64::Engine;
use gmgn_agent_runtime::{
    cli_transport::{CliConfig, OwnedCliTransport},
    dsh_session::{DshEvent, DshSession, DshState},
    CancellationToken, HostToolContext, HostToolExecutor, HostToolReceipt, HostToolStatus,
    ImageInput, ToolCall, ToolExecutionContext, TurnIdentity, UserInput,
};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::{
    collections::{BTreeMap, HashMap, HashSet},
    future::Future,
    path::PathBuf,
    pin::Pin,
    sync::{
        atomic::{AtomicBool, AtomicUsize, Ordering},
        Arc,
    },
    time::Duration,
};
use tokio::sync::{oneshot, Mutex};
type Result<T> = std::result::Result<T, &'static str>;
type ToolFuture<T> = Pin<Box<dyn Future<Output = std::result::Result<T, String>> + Send + 'static>>;
fn text(p: &Value, k: &str) -> Result<String> {
    p[k].as_str()
        .filter(|v| !v.is_empty() && v.len() <= 256)
        .map(str::to_owned)
        .ok_or("agent_dsh_invalid_request")
}
fn identity(p: &Value) -> Result<TurnIdentity> {
    Ok(TurnIdentity {
        world_id: text(p, "worldID")?,
        scope_id: text(p, "residentScope")?,
        session_id: text(p, "hostSessionID")?,
        run_id: text(p, "runID")?,
    })
}
fn params(i: &TurnIdentity) -> Value {
    json!({"worldID":i.world_id,"residentScope":i.scope_id,"hostSessionID":i.session_id,"runID":i.run_id})
}
fn quote(v: &str) -> Result<String> {
    if v.is_empty() || v.contains(['\n', '\r', '\0']) {
        return Err("agent_dsh_unsafe_configuration");
    }
    Ok(v.replace('\'', "''"))
}
fn composition(p: &Value) -> Result<String> {
    let attachment = quote(
        p["attachmentHome"]
            .as_str()
            .ok_or("agent_dsh_invalid_configuration")?,
    )?;
    let persistence = quote(
        p["persistenceRoot"]
            .as_str()
            .ok_or("agent_dsh_invalid_configuration")?,
    )?;
    let persona = quote(
        p["persona"]
            .as_str()
            .filter(|v| v.len() <= 65536)
            .ok_or("agent_dsh_invalid_configuration")?,
    )?;
    let plugin = quote(
        p["hostToolsPlugin"]
            .as_str()
            .ok_or("agent_dsh_invalid_configuration")?,
    )?;
    if !attachment.starts_with('/')
        || !persistence.starts_with('/')
        || !plugin.starts_with('/')
        || !plugin.ends_with("/gmgn-host-tools.mjs")
    {
        return Err("agent_dsh_invalid_configuration");
    }
    if p.get("mcpServer").is_some() {
        return Err("agent_dsh_unsupported_mcp_configuration");
    }
    // Exact emitted grammar of ResidentDSHComposition; no arbitrary YAML features.
    Ok(format!("# Generated by gmgn ResidentDSHConfiguration; re-validated by read-back before every launch.\n- id: llm-deepseek\n  name: '@deepseek-ai/dsh-llm-deepseek'\n  config:\n    reasoningEffort: low\n    maxTokens: 8192\n    models:\n      - id: deepseek-flash\n        inputModalities: [text, image]\n      - id: deepseek-v4-pro\n        inputModalities: [text]\n- id: credentials\n  name: '@deepseek-ai/dsh-credentials-local'\n- id: attachment-local\n  name: '@deepseek-ai/dsh-attachment-local'\n  config:\n    dshHome: '{attachment}'\n- id: acp-agent\n  name: '@deepseek-ai/dsh-acp-demo'\n  config:\n    provider: deepseek-official\n    model: deepseek-flash\n    persistenceRoot: '{persistence}'\n    packChunks: false\n    persistenceCompression: none\n    workspaceContext: false\n    toolBash: false\n    toolJobs: false\n    goals: false\n    skills:\n      enabled: false\n    tools:\n      mode: native\n    persona: '{persona}'\n- id: web\n  name: '@deepseek-ai/dsh-web'\n  config:\n    searchProvider: deepseek-official\n- id: web-fetch-http\n  name: '@deepseek-ai/dsh-web-fetch-http'\n- id: web-search-deepseek\n  name: '@deepseek-ai/dsh-web-search-deepseek'\n- id: tool-web\n  name: '@deepseek-ai/dsh-tool-web'\n- id: gmgn-host-tools\n  name: '{plugin}'"))
}
fn image_blocks(p: &Value) -> Result<Vec<ImageInput>> {
    let Some(raw) = p.get("images") else {
        return Ok(vec![]);
    };
    let raw = raw
        .as_array()
        .filter(|v| v.len() <= 4)
        .ok_or("agent_dsh_image_limit")?;
    let mut total = 0;
    let mut images = Vec::new();
    for image in raw {
        let media_type = image["mediaType"]
            .as_str()
            .ok_or("agent_dsh_invalid_image")?
            .to_owned();
        let encoded = image["base64"]
            .as_str()
            .filter(|v| v.len() <= 6 * 1024 * 1024)
            .ok_or("agent_dsh_image_limit")?;
        let bytes = base64::engine::general_purpose::STANDARD
            .decode(encoded)
            .map_err(|_| "agent_dsh_invalid_image")?;
        total += bytes.len();
        if bytes.is_empty() || total > 4 * 1024 * 1024 {
            return Err("agent_dsh_image_limit");
        }
        let valid = match media_type.as_str() {
            "image/png" => bytes.starts_with(b"\x89PNG\r\n\x1a\n"),
            "image/jpeg" => bytes.starts_with(b"\xff\xd8\xff"),
            "image/gif" => bytes.starts_with(b"GIF87a") || bytes.starts_with(b"GIF89a"),
            "image/webp" => bytes.starts_with(b"RIFF") && bytes.get(8..12) == Some(b"WEBP"),
            _ => false,
        };
        if !valid {
            return Err("agent_dsh_invalid_image");
        }
        images.push(ImageInput { bytes, media_type });
    }
    Ok(images)
}
fn environment(p: &Value) -> Result<BTreeMap<String, String>> {
    let mut env = BTreeMap::new();
    let raw = p.as_object().ok_or("agent_dsh_invalid_environment")?;
    if raw.len() > 128 {
        return Err("agent_dsh_invalid_environment");
    }
    for key in ["HOME", "TMPDIR", "LANG", "LC_ALL", "USER", "LOGNAME"] {
        if let Some(v) = raw.get(key) {
            let v = v
                .as_str()
                .filter(|v| !v.contains('\0') && v.len() <= 4096)
                .ok_or("agent_dsh_invalid_environment")?;
            if !v.is_empty() {
                env.insert(key.into(), v.into());
            }
        }
    }
    env.insert(
        "PATH".into(),
        "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin".into(),
    );
    Ok(env)
}
struct Configuration {
    process: CliConfig,
    input: UserInput,
    tools: Value,
    names: HashMap<String, String>,
    silent: bool,
}
impl Configuration {
    fn parse(p: &Value) -> Result<Self> {
        let executable = PathBuf::from(
            p["executable"]
                .as_str()
                .ok_or("agent_dsh_invalid_configuration")?,
        );
        let entry = PathBuf::from(
            p["entryPoint"]
                .as_str()
                .ok_or("agent_dsh_invalid_configuration")?,
        );
        let config = PathBuf::from(
            p["compositionFile"]
                .as_str()
                .ok_or("agent_dsh_invalid_configuration")?,
        );
        let root = PathBuf::from(
            p["root"]
                .as_str()
                .ok_or("agent_dsh_invalid_configuration")?,
        );
        let cwd = PathBuf::from(p["cwd"].as_str().ok_or("agent_dsh_invalid_configuration")?);
        if [&executable, &entry, &config, &root, &cwd]
            .iter()
            .any(|p| !p.is_absolute())
        {
            return Err("agent_dsh_invalid_configuration");
        }
        let root = root
            .canonicalize()
            .map_err(|_| "agent_dsh_invalid_configuration")?;
        let cwd = cwd
            .canonicalize()
            .map_err(|_| "agent_dsh_invalid_configuration")?;
        let config = config
            .canonicalize()
            .map_err(|_| "agent_dsh_invalid_configuration")?;
        if !cwd.starts_with(&root) || !config.starts_with(&root) || !cwd.is_dir() {
            return Err("agent_dsh_unsafe_configuration");
        }
        let expected = composition(p)?;
        let size = std::fs::metadata(&config)
            .map_err(|_| "agent_dsh_invalid_configuration")?
            .len();
        if size > 131072 {
            return Err("agent_dsh_unsafe_configuration");
        }
        let actual =
            std::fs::read_to_string(&config).map_err(|_| "agent_dsh_invalid_configuration")?;
        if actual.trim() != expected.trim() {
            return Err("agent_dsh_unsafe_configuration");
        }
        for key in ["attachmentHome", "persistenceRoot"] {
            let path = PathBuf::from(p[key].as_str().ok_or("agent_dsh_invalid_configuration")?)
                .canonicalize()
                .map_err(|_| "agent_dsh_invalid_configuration")?;
            if !path.starts_with(&root) {
                return Err("agent_dsh_unsafe_configuration");
            }
        }
        let expected_args = vec![
            entry.to_string_lossy().into_owned(),
            "--config".into(),
            config.to_string_lossy().into_owned(),
        ];
        let args = p["arguments"]
            .as_array()
            .ok_or("agent_dsh_invalid_configuration")?
            .iter()
            .map(|v| {
                v.as_str()
                    .map(str::to_owned)
                    .ok_or("agent_dsh_invalid_configuration")
            })
            .collect::<Result<Vec<_>>>()?;
        if args != expected_args {
            return Err("agent_dsh_unsafe_arguments");
        }
        let tools = p["tools"]
            .as_array()
            .filter(|v| !v.is_empty() && v.len() <= 64)
            .ok_or("agent_dsh_invalid_tools")?;
        let mut names = HashMap::new();
        for t in tools {
            let name = text(t, "name")?;
            let declared = format!("gmgn_{name}");
            if name.starts_with("gmgn_")
                || declared.chars().count() > 64
                || !declared
                    .chars()
                    .all(|c| c.is_alphanumeric() || c == '_' || c == '-')
                || t["inputSchema"]["type"] != "object"
                || names.insert(declared, name).is_some()
            {
                return Err("agent_dsh_invalid_tools");
            }
        }
        let input = p["input"]
            .as_str()
            .filter(|v| v.len() <= 65536)
            .ok_or("agent_dsh_invalid_input")?
            .to_owned();
        let images = image_blocks(p)?;
        if input.trim().is_empty() && images.is_empty() {
            return Err("agent_dsh_invalid_input");
        }
        Ok(Self {
            process: CliConfig {
                executable,
                arguments: args,
                environment: environment(&p["environment"])?,
                working_directory: Some(cwd),
                lifetime: Duration::from_secs(600),
            },
            input: UserInput {
                text: input,
                images,
            },
            tools: json!(tools),
            names,
            silent: p["allowSilentCompletion"].as_bool().unwrap_or(false),
        })
    }
}
struct Approval {
    request: Value,
    tx: oneshot::Sender<std::result::Result<String, String>>,
}
struct Execution {
    request: Value,
    tx: oneshot::Sender<HostToolReceipt>,
}
#[derive(Default)]
struct Queue {
    approval: Mutex<HashMap<String, Approval>>,
    execution: Mutex<HashMap<String, Execution>>,
    approved: Mutex<HashMap<String, Value>>,
    completed: Mutex<HashMap<String, Value>>,
    event: Mutex<String>,
    acp_session: Mutex<Option<String>>,
}
struct Cleanup {
    q: Arc<Queue>,
    call: String,
    approval: bool,
}
impl Drop for Cleanup {
    fn drop(&mut self) {
        let q = self.q.clone();
        let call = self.call.clone();
        let approval = self.approval;
        if let Ok(handle) = tokio::runtime::Handle::try_current() {
            handle.spawn(async move {
                if approval {
                    q.approval.lock().await.remove(&call);
                } else {
                    q.execution.lock().await.remove(&call);
                }
            });
        }
    }
}
async fn proposal(
    q: &Queue,
    c: &HostToolContext,
    phase: &str,
) -> std::result::Result<Value, String> {
    let mut p = params(&c.identity);
    p["eventID"] = json!(q.event.lock().await.clone());
    p["acpSessionID"] = json!(q
        .acp_session
        .lock()
        .await
        .clone()
        .ok_or("dsh_session_not_ready")?);
    p["callID"] = json!(c.execution.call.tool_call_id);
    p["toolName"] = json!(c.execution.call.tool_name);
    p["arguments"] = c.execution.call.input.clone();
    p["phase"] = json!(phase);
    Ok(p)
}
struct Resolver(Arc<Queue>);
impl BusinessOperationResolver for Resolver {
    fn resolve(&self, _: &TurnIdentity, _: &str, _: &Value) -> std::result::Result<String, String> {
        Err("host_authorization_required".into())
    }
    fn resolve_context(&self, c: HostToolContext) -> ToolFuture<String> {
        let q = self.0.clone();
        Box::pin(async move {
            let call = c.execution.call.tool_call_id.clone();
            let request = proposal(&q, &c, "authorize").await?;
            let (tx, rx) = oneshot::channel();
            {
                let mut pending = q.approval.lock().await;
                if pending.len() >= 16 || pending.contains_key(&call) {
                    return Err("host_queue_limit".into());
                }
                pending.insert(call.clone(), Approval { request, tx });
            }
            let _cleanup = Cleanup {
                q,
                call,
                approval: true,
            };
            tokio::select! {biased;_=c.execution.cancellation.cancelled()=>Err("host_authorization_cancelled".into()),r=tokio::time::timeout(Duration::from_secs(120),rx)=>match r{Ok(Ok(v))=>v,_=>Err("host_authorization_unavailable".into())}}
        })
    }
}
struct Transport(Arc<Queue>);
impl HostToolTransport for Transport {
    fn dispatch(&self, c: HostToolContext, operation: String) -> ToolFuture<HostToolReceipt> {
        let q = self.0.clone();
        Box::pin(async move {
            let call = c.execution.call.tool_call_id.clone();
            let mut request = proposal(&q, &c, "execute").await?;
            request["operationID"] = json!(operation);
            let (tx, rx) = oneshot::channel();
            {
                let mut pending = q.execution.lock().await;
                if pending.len() >= 16 || pending.contains_key(&call) {
                    return Err("host_queue_limit".into());
                }
                pending.insert(call.clone(), Execution { request, tx });
            }
            let _cleanup = Cleanup {
                q,
                call,
                approval: false,
            };
            tokio::select! {biased;_=c.execution.cancellation.cancelled()=>Err("host_tool_unknown".into()),r=tokio::time::timeout(Duration::from_secs(120),rx)=>match r{Ok(Ok(v))=>Ok(v),_=>Err("host_tool_unknown".into())}}
        })
    }
}
struct Session {
    identity: TurnIdentity,
    event: String,
    token: String,
    names: HashMap<String, String>,
    executor: Arc<LedgerHostTools>,
    queue: Arc<Queue>,
    state: Mutex<String>,
    text: Mutex<String>,
    cancel: CancellationToken,
    user_cancelled: AtomicBool,
    active: AtomicUsize,
    success: AtomicUsize,
    calls: Mutex<HashSet<String>>,
}
/// A refused host receipt is not a receipt: the effect stays unconfirmed either
/// way. What must not happen is the host future waiting on it parking until the
/// 120 s transport bound with nobody left to answer — that is the "报一个错、
/// 改一个错" shape the 2026-10-09 sweep removed. Settle the pending execution as
/// `Unknown` immediately (the executor then writes the same durable `unknown`
/// row), and still return the named refusal so the caller learns why.
async fn refuse_receipt(s: &Session, call: &str, code: &'static str) -> Result<Value> {
    let execution = s.queue.execution.lock().await.remove(call);
    if let Some(execution) = execution {
        let _ = execution.tx.send(HostToolReceipt {
            identity: s.identity.clone(),
            call_id: call.to_owned(),
            status: HostToolStatus::Unknown,
            output: json!({"error":"host_receipt_refused"}),
            images: Vec::new(),
        });
    }
    Err(code)
}
pub struct DshService {
    db: Database,
    session: Mutex<Option<Arc<Session>>>,
}
impl DshService {
    pub fn new(db: Database) -> Self {
        Self {
            db,
            session: Mutex::new(None),
        }
    }
    /// Only the live turn's private plugin token may enter the flat HTTP branch.
    pub async fn accepts_grant(&self, bearer: &str) -> bool {
        let session = self.session.lock().await.clone();
        let Some(session) = session else {
            return false;
        };
        !bearer.is_empty()
            && bearer == session.token
            && !session.cancel.is_cancelled()
            && *session.state.lock().await == "running"
    }
    async fn claimed(&self, i: &TurnIdentity, event: &str) -> Result<()> {
        let p = params(i);
        let event = event.to_owned();
        self.db
            .call(move |store| {
                let state = agent_scheduler::request(&mut store.connection, "agent_loop_read", &p)?;
                if state["config"]["hostSessionID"] != p["hostSessionID"] {
                    return Err("agent_dsh_stale_session");
                }
                if !state["events"].as_array().is_some_and(|v| {
                    v.iter().any(|e| {
                        e["eventID"] == event
                            && e["runID"] == p["runID"]
                            && e["hostSessionID"] == p["hostSessionID"]
                            && e["state"] == "claimed"
                    })
                }) {
                    return Err("agent_dsh_run_not_claimed");
                }
                Ok(())
            })
            .await
    }
    async fn current(&self, i: &TurnIdentity, event: &Value) -> Result<Arc<Session>> {
        let s = self
            .session
            .lock()
            .await
            .clone()
            .ok_or("agent_dsh_not_started")?;
        if s.identity != *i || event.as_str() != Some(s.event.as_str()) {
            return Err("agent_dsh_stale_session");
        }
        let p = params(i);
        self.db
            .call(move |store| {
                let state = agent_scheduler::request(&mut store.connection, "agent_loop_read", &p)?;
                if state["config"]["hostSessionID"] != p["hostSessionID"] {
                    return Err("agent_dsh_stale_session");
                }
                Ok(())
            })
            .await?;
        Ok(s)
    }
    pub async fn request(&self, method: &str, p: &Value) -> Result<Value> {
        let i = identity(p)?;
        match method {
            "agent_dsh_start" => {
                let event = text(p, "eventID")?;
                // The trusted host installs this private grant before starting ACP.
                let token = text(p, "grantToken")?;
                if uuid::Uuid::parse_str(&token).is_err()
                    || uuid::Uuid::parse_str(&token).unwrap().get_version_num() != 4
                {
                    return Err("agent_dsh_invalid_configuration");
                }
                self.claimed(&i, &event).await?;
                let ledger_identity = params(&i);
                // "Unresolved" is only a reason to refuse a new turn while it can
                // still be produced. An `inflight` row is a dispatch this daemon
                // started and whose host future is bounded by the 120 s transport
                // window (`Transport::dispatch`), so it is always live. An
                // `unknown` row is a durable "we never learned the effect" fact:
                // it is live only while the run that owns it is still claimed.
                //
                // Counting every `unknown` row for the whole world+scope (the
                // rule until 2026-10-09) made one refused host receipt lock the
                // resident out of chat for the life of the database: nothing on
                // the DSH path ever calls `agent_runtime_reconcile`, and the
                // in-memory session check below refused too. The record is kept —
                // it is never rewritten to `applied`/`not_applied` without the
                // host's own verification — it simply stops gating unrelated
                // turns. The same operation is still protected by
                // `agent_tool_operation_blocked` at `agent_tool_begin`.
                let (blocked, stale) = self
                    .db
                    .call(move |store| {
                        let live: i64 = store.connection.query_row(
                            "SELECT count(*) FROM agent_tool_calls c JOIN agent_loop_events e ON e.world=c.world AND e.scope=c.scope AND e.run=c.run \
                             WHERE c.world=?1 AND c.scope=?2 AND (c.state='inflight' OR (c.state='unknown' AND e.state IN ('claimed','cancel_requested')))",
                            rusqlite::params![ledger_identity["worldID"].as_str(),ledger_identity["residentScope"].as_str()],
                            |row| row.get(0)).map_err(|_|"storage_unavailable")?;
                        let stale: i64 = store.connection.query_row(
                            "SELECT count(*) FROM agent_tool_calls c WHERE c.world=?1 AND c.scope=?2 AND c.state='unknown' \
                             AND NOT EXISTS (SELECT 1 FROM agent_loop_events e WHERE e.world=c.world AND e.scope=c.scope AND e.run=c.run AND e.state IN ('claimed','cancel_requested'))",
                            rusqlite::params![ledger_identity["worldID"].as_str(),ledger_identity["residentScope"].as_str()],
                            |row| row.get(0)).map_err(|_|"storage_unavailable")?;
                        Ok((live, stale))
                    })
                    .await?;
                if stale > 0 {
                    // Named, readable, and never silent: the effect of these calls
                    // is still unconfirmed, we just no longer pretend a new turn
                    // could learn it.
                    eprintln!(
                        "gmgn-taskd: {}",
                        json!({
                            "event": "recovered",
                            "code": "agent_dsh_stale_unconfirmed_tools",
                            "worldID": i.world_id,
                            "residentScope": i.scope_id,
                            "count": stale,
                        })
                    );
                }
                if blocked > 0 {
                    return Err("agent_dsh_unresolved_tools");
                }
                let config = Configuration::parse(p)?;
                let mut current = self.session.lock().await;
                if let Some(old) = current.as_ref() {
                    let previous = old.state.lock().await.clone();
                    // `unknown` is written only at the end of `run`, after the ACP
                    // child was reaped and every cancelled host future got its 2 s
                    // settle window: the session is dead, nothing can advance it.
                    // Refusing to replace it (the rule until 2026-10-09) turned one
                    // uncertain turn into a permanent `agent_dsh_session_busy` for
                    // the whole resident scope.
                    if old.token == token
                        || !["completed", "failed", "cancelled", "unknown"]
                            .contains(&previous.as_str())
                    {
                        return Err("agent_dsh_session_busy");
                    }
                }
                let queue = Arc::new(Queue::default());
                *queue.event.lock().await = event.clone();
                let executor = Arc::new(LedgerHostTools::new(
                    self.db.clone(),
                    Arc::new(Resolver(queue.clone())),
                    Arc::new(Transport(queue.clone())),
                ));
                executor
                    .register(&i, config.tools.clone())
                    .await
                    .map_err(|_| "agent_dsh_invalid_tools")?;
                let s = Arc::new(Session {
                    identity: i,
                    event,
                    token,
                    names: config.names.clone(),
                    executor,
                    queue,
                    state: Mutex::new("starting".into()),
                    text: Mutex::new(String::new()),
                    cancel: CancellationToken::new(),
                    user_cancelled: AtomicBool::new(false),
                    active: AtomicUsize::new(0),
                    success: AtomicUsize::new(0),
                    calls: Mutex::new(HashSet::new()),
                });
                let token = s.token.clone();
                *current = Some(s.clone());
                let db = self.db.clone();
                tokio::spawn(async move {
                    run(db, s, config).await;
                });
                Ok(json!({"started":true,"grantToken":token}))
            }
            "agent_dsh_read" => {
                let s = self.current(&i, &p["eventID"]).await?;
                let mut pending = s
                    .queue
                    .approval
                    .lock()
                    .await
                    .values()
                    .map(|v| v.request.clone())
                    .collect::<Vec<_>>();
                pending.extend(
                    s.queue
                        .execution
                        .lock()
                        .await
                        .values()
                        .map(|v| v.request.clone()),
                );
                Ok(
                    json!({"state":s.state.lock().await.clone(),"text":s.text.lock().await.clone(),"pendingTools":pending,"acpSessionID":s.queue.acp_session.lock().await.clone()}),
                )
            }
            "agent_dsh_authorize" => {
                let s = self.current(&i, &p["eventID"]).await?;
                let call = text(p, "callID")?;
                let decision = text(p, "decision")?;
                let operation = match decision.as_str() {
                    "approved" => Some(text(p, "operationID")?),
                    "rejected" => None,
                    _ => return Err("agent_dsh_invalid_authorization"),
                };
                let answer = json!({"acpSessionID":text(p,"acpSessionID")?,"toolName":text(p,"toolName")?,"arguments":p["arguments"],"decision":decision,"operationID":operation});
                let mut pending = s.queue.approval.lock().await;
                let mut done = s.queue.approved.lock().await;
                if let Some(old) = done.get(&call) {
                    if *old != answer {
                        return Err("agent_dsh_receipt_conflict");
                    }
                    return Ok(json!({"accepted":true,"duplicate":true}));
                }
                if s.cancel.is_cancelled() {
                    return Err("agent_dsh_not_pending");
                }
                let proposal = pending.get(&call).ok_or("agent_dsh_not_pending")?;
                for k in ["acpSessionID", "toolName", "arguments"] {
                    if proposal.request[k] != answer[k] {
                        return Err("agent_dsh_receipt_conflict");
                    }
                }
                let proposal = pending.remove(&call).unwrap();
                proposal
                    .tx
                    .send(operation.ok_or_else(|| "host_operation_rejected".into()))
                    .map_err(|_| "agent_dsh_not_pending")?;
                done.insert(call, answer);
                Ok(json!({"accepted":true,"duplicate":false}))
            }
            "agent_dsh_tool_receipt" => {
                let s = self.current(&i, &p["eventID"]).await?;
                let call = text(p, "callID")?;
                let images = image_blocks(p)?;
                // The result half of a receipt is the **host's** own payload (for
                // `inspect_world` it is the whole visible snapshot plus the movement
                // path), so it is measured against `MAXIMUM_RECEIPT_BYTES`, not the
                // 16 KiB bound the model's own arguments are held to. A refusal names
                // the field and the measured size instead of being anonymous.
                let output_bytes = p["output"].to_string().len();
                if images.len() > 1 || output_bytes > crate::agent_tools::MAXIMUM_RECEIPT_BYTES {
                    eprintln!(
                        "gmgn-taskd: {}",
                        json!({
                            "event": "rejected",
                            "code": "agent_dsh_invalid_receipt",
                            "method": "agent_dsh_tool_receipt",
                            "tool": &call,
                            "path": if images.len() > 1 { "$.images" } else { "$.output" },
                            "detail": if images.len() > 1 {
                                format!("receipt carries {} images, above the 1 image limit", images.len())
                            } else {
                                format!("host result is {} bytes, above the {} byte limit", output_bytes, crate::agent_tools::MAXIMUM_RECEIPT_BYTES)
                            },
                        })
                    );
                    return refuse_receipt(&s, &call, "agent_dsh_invalid_receipt").await;
                }
                let answer = json!({"acpSessionID":text(p,"acpSessionID")?,"operationID":text(p,"operationID")?,"status":p["status"],"output":p["output"],"images":images.iter().map(|v|json!({"mediaType":v.media_type,"byteLength":v.bytes.len(),"sha256":format!("{:x}",Sha256::digest(&v.bytes))})).collect::<Vec<_>>()});
                let mut pending = s.queue.execution.lock().await;
                let mut done = s.queue.completed.lock().await;
                if let Some(old) = done.get(&call) {
                    if *old != answer {
                        return Err("agent_dsh_receipt_conflict");
                    }
                    return Ok(json!({"accepted":true,"duplicate":true}));
                }
                let execution = pending.get(&call).ok_or("agent_dsh_not_pending")?;
                for k in ["acpSessionID", "operationID"] {
                    if execution.request[k] != answer[k] {
                        return Err("agent_dsh_receipt_conflict");
                    }
                }
                let prior_count = done
                    .values()
                    .filter_map(|v| v["images"].as_array())
                    .map(Vec::len)
                    .sum::<usize>();
                let prior_bytes = done
                    .values()
                    .filter_map(|v| v["images"].as_array())
                    .flatten()
                    .filter_map(|v| v["byteLength"].as_u64())
                    .sum::<u64>();
                if prior_count + images.len() > 4
                    || prior_bytes + images.iter().map(|v| v.bytes.len() as u64).sum::<u64>()
                        > 4 * 1024 * 1024
                {
                    // The execution entry is already locked here, so settle it in
                    // place: a refused receipt must not leave the host future on
                    // the 120 s bound.
                    if let Some(execution) = pending.remove(&call) {
                        let _ = execution.tx.send(HostToolReceipt {
                            identity: i.clone(),
                            call_id: call.clone(),
                            status: HostToolStatus::Unknown,
                            output: json!({"error":"host_receipt_refused"}),
                            images: Vec::new(),
                        });
                    }
                    return Err("agent_dsh_image_limit");
                }
                let status = match p["status"].as_str() {
                    Some("completed") => HostToolStatus::Completed,
                    Some("unknown") => HostToolStatus::Unknown,
                    Some("rejected") => HostToolStatus::Rejected,
                    other => {
                        eprintln!(
                            "gmgn-taskd: {}",
                            json!({
                                "event": "rejected",
                                "code": "agent_dsh_invalid_receipt",
                                "method": "agent_dsh_tool_receipt",
                                "tool": &call,
                                "path": "$.status",
                                "detail": match other {
                                    Some(value) => format!("host status {:?} is not one of completed/unknown/rejected", value.chars().take(32).collect::<String>()),
                                    None => "host status is missing or not a string".to_owned(),
                                },
                            })
                        );
                        if let Some(execution) = pending.remove(&call) {
                            let _ = execution.tx.send(HostToolReceipt {
                                identity: i.clone(),
                                call_id: call.clone(),
                                status: HostToolStatus::Unknown,
                                output: json!({"error":"host_receipt_refused"}),
                                images: Vec::new(),
                            });
                        }
                        return Err("agent_dsh_invalid_receipt");
                    }
                };
                let execution = pending.remove(&call).unwrap();
                execution
                    .tx
                    .send(HostToolReceipt {
                        identity: i,
                        call_id: call.clone(),
                        status,
                        output: p["output"].clone(),
                        images,
                    })
                    .map_err(|_| "agent_dsh_not_pending")?;
                done.insert(call, answer);
                Ok(json!({"accepted":true,"duplicate":false}))
            }
            "agent_dsh_cancel" => {
                let s = self.current(&i, &p["eventID"]).await?;
                let mut cancel = params(&i);
                cancel["eventID"] = json!(s.event);
                let result = self
                    .db
                    .call(move |store| {
                        agent_scheduler::request(
                            &mut store.connection,
                            "agent_loop_cancel",
                            &cancel,
                        )
                    })
                    .await?;
                if result["cancelRequested"] == true {
                    s.user_cancelled.store(true, Ordering::Release);
                    *s.state.lock().await = "cancel_requested".into();
                    s.cancel.cancel();
                }
                Ok(result)
            }
            _ => Err("unknown_method"),
        }
    }
    /// Dedicated daemon HTTP /rpc flat-plugin route; token never authorizes control RPCs.
    pub async fn host_call(&self, bearer: &str, p: &Value) -> Result<Value> {
        let fields = p.as_object().ok_or("agent_dsh_invalid_request")?;
        if fields.len() != 4
            || !["v", "callId", "name", "arguments"]
                .iter()
                .all(|key| fields.contains_key(*key))
        {
            return Err("agent_dsh_invalid_request");
        }
        let s = self
            .session
            .lock()
            .await
            .clone()
            .ok_or("agent_dsh_not_started")?;
        if bearer != s.token
            || s.cancel.is_cancelled()
            || *s.state.lock().await != "running"
            || p["v"] != 1
        {
            return Err("agent_dsh_host_unauthorized");
        }
        self.claimed(&s.identity, &s.event).await?;
        let call = p["callId"]
            .as_str()
            .filter(|v| !v.is_empty() && v.len() <= 256)
            .ok_or("agent_dsh_invalid_request")?
            .to_owned();
        let name = p["name"].as_str().ok_or("agent_dsh_invalid_request")?;
        let tool = s
            .names
            .get(name)
            .cloned()
            .ok_or("agent_dsh_tool_not_authorized")?;
        if !p["arguments"].is_object() || p["arguments"].to_string().len() > 16384 {
            return Err("agent_dsh_invalid_request");
        }
        {
            let mut calls = s.calls.lock().await;
            if calls.len() >= 128 || !calls.insert(call.clone()) {
                return Err("agent_dsh_duplicate_call");
            }
        }
        if s.active.fetch_add(1, Ordering::AcqRel) >= 16 {
            s.active.fetch_sub(1, Ordering::AcqRel);
            return Err("agent_dsh_queue_limit");
        }
        struct Active(Arc<Session>);
        impl Drop for Active {
            fn drop(&mut self) {
                self.0.active.fetch_sub(1, Ordering::AcqRel);
            }
        }
        let _active = Active(s.clone());
        let receipt = s
            .executor
            .execute(HostToolContext {
                identity: s.identity.clone(),
                execution: ToolExecutionContext {
                    call: ToolCall {
                        tool_call_id: call,
                        tool_name: tool,
                        input: p["arguments"].clone(),
                        provider_executed: None,
                        dynamic: None,
                        thought_signature: None,
                    },
                    cancellation: s.cancel.clone(),
                },
            })
            .await;
        match receipt {
            Ok(receipt) => {
                if s.cancel.is_cancelled() {
                    return Err("agent_dsh_host_result_unknown");
                }
                if receipt.status == HostToolStatus::Rejected {
                    // The host answered this one call and refused it. That is not
                    // a session failure: cancelling here (the rule until
                    // 2026-10-09) turned one bad motion id into a dead turn, with
                    // the model told only `host_tool_unavailable` instead of the
                    // host's own code. Hand the host's answer back verbatim, do
                    // not count it as a success, and let the agent try something
                    // else in the same turn.
                    let code = receipt
                        .output
                        .get("code")
                        .and_then(Value::as_str)
                        .or_else(|| receipt.output.get("error").and_then(Value::as_str))
                        .unwrap_or("host_tool_unavailable");
                    let message = receipt
                        .output
                        .get("message")
                        .and_then(Value::as_str)
                        .unwrap_or("宿主拒绝了这次调用。");
                    return Ok(json!({"ok":false,"error":{"code":code,"message":message}}));
                }
                s.success.fetch_add(1, Ordering::AcqRel);
                let mut reply = json!({"ok":true,"data":receipt.output});
                if let Some(image) = receipt.images.first() {
                    reply["image"] = json!({"base64":base64::engine::general_purpose::STANDARD.encode(&image.bytes),"mimeType":image.media_type});
                }
                Ok(reply)
            }
            Err(reason) => {
                if reason != "host_operation_unavailable" {
                    s.cancel.cancel();
                }
                Ok(
                    json!({"ok":false,"error":{"code":"host_tool_unavailable","message":"宿主工具未能完成。"}}),
                )
            }
        }
    }
}
async fn run(db: Database, s: Arc<Session>, config: Configuration) {
    let allow_silent = config.silent;
    let result = drive(s.clone(), config).await;
    // The ACP child is already reaped. Give cancelled host futures time to
    // settle their own ledger guards; never release a still-running effect.
    let settling = tokio::time::Instant::now() + Duration::from_secs(2);
    while s.active.load(Ordering::Acquire) > 0 && tokio::time::Instant::now() < settling {
        tokio::time::sleep(Duration::from_millis(10)).await;
    }
    let mut p = params(&s.identity);
    p["eventID"] = json!(s.event);
    let unknown=db.call({let p=p.clone();move|store|store.connection.query_row("SELECT count(*) FROM agent_tool_calls WHERE world=?1 AND scope=?2 AND run=?3 AND state IN ('unknown','inflight')",rusqlite::params![p["worldID"].as_str(),p["residentScope"].as_str(),p["runID"].as_str()],|r|r.get::<_,i64>(0)).map_err(|_|"storage_unavailable")}).await.unwrap_or(1)>0;
    let (state, reply) = result.unwrap_or((DshState::Unknown, String::new()));
    if unknown || s.active.load(Ordering::Acquire) > 0 || state == DshState::Unknown {
        // The ACP child is reaped and this run still owns a call whose effect was
        // never learned (or the child's own outcome is unknown). Two facts must
        // survive, and until 2026-10-09 neither did:
        //
        //   * the **call** stays `unknown` — never rewritten to applied/not_applied
        //     without the host's own verification, and still blocking its own
        //     operation at `agent_tool_begin`;
        //   * the **turn** must not be seized by the daemon. This arm used to write
        //     `agent_loop_events.state='unknown'` itself, which made the host's own
        //     `agent_loop_complete` fail as `agent_loop_receipt_conflict` (its
        //     `resident_model_turn` receipt can never equal one this daemon
        //     invented), left the human-message row dangling in `claimed`, and
        //     surfaced to the client as `RustDSHSessionClient error 4`
        //     (`ClientError.unknownExecution`), which discards the whole turn —
        //     streamed reply included.
        //
        // The turn receipt belongs to the host; the daemon only names the session
        // outcome. `failed` is the honest name (the turn did not complete), and it
        // is terminal, so the client returns a named result instead of `unknown`
        // and the host's own settle lands on a still-`claimed` event.
        *s.state.lock().await = "failed".into();
        return;
    }
    let status = if s.user_cancelled.load(Ordering::Acquire) && state == DshState::Cancelled {
        "cancelled"
    } else if state == DshState::Completed
        && (!reply.trim().is_empty() || (allow_silent && s.success.load(Ordering::Acquire) > 0))
    {
        "completed"
    } else {
        "failed"
    };
    *s.text.lock().await = reply;
    p["status"] = json!(status);
    p["receipt"] =
        json!({"source":"native-dsh-acp","status":status,"reply":s.text.lock().await.clone()});
    let method = if status == "cancelled" {
        "agent_loop_confirm_cancel"
    } else {
        "agent_loop_complete"
    };
    let settled = db
        .call(move |store| agent_scheduler::request(&mut store.connection, method, &p))
        .await;
    *s.state.lock().await = if settled.is_ok() { status } else { "unknown" }.into();
}
async fn drive(s: Arc<Session>, config: Configuration) -> Result<(DshState, String)> {
    if s.cancel.is_cancelled() {
        return Ok((DshState::Cancelled, String::new()));
    }
    let cwd = config
        .process
        .working_directory
        .as_ref()
        .ok_or("agent_dsh_invalid_configuration")?
        .to_string_lossy()
        .into_owned();
    let mut protocol = DshSession::new(s.identity.clone(), cwd, config.input, config.silent)
        .map_err(|_| "agent_dsh_invalid_input")?;
    let mut transport = OwnedCliTransport::spawn(config.process)
        .await
        .map_err(|_| "agent_dsh_launch_failed")?;
    transport
        .send(
            &protocol
                .initialize()
                .map_err(|_| "agent_dsh_protocol_failed")?,
        )
        .await
        .map_err(|_| "agent_dsh_transport_failed")?;
    let mut cancelled = false;
    let mut prompted = false;
    let mut deadline = tokio::time::Instant::now() + Duration::from_secs(600);
    let terminal = loop {
        let events = tokio::select! {biased;_=s.cancel.cancelled(),if !cancelled=>{cancelled=true;deadline=tokio::time::Instant::now()+Duration::from_secs(8);protocol.cancel()},_=tokio::time::sleep_until(deadline)=>protocol.disconnected(),frame=transport.receive()=>match frame{Ok(frame)=>match protocol.receive(frame){Ok(events)=>events,Err(_)=>break(if prompted{DshState::Unknown}else{DshState::Failed},String::new())},Err(_)=>protocol.disconnected()}};
        let mut terminal = None;
        for event in events {
            match event {
                DshEvent::Send(frame) => {
                    if frame["method"] == "session/prompt" {
                        prompted = true;
                    }
                    if transport.send(&frame).await.is_err() {
                        terminal = Some((DshState::Unknown, String::new()));
                        break;
                    }
                }
                DshEvent::SessionReady { session_id, .. } => {
                    *s.queue.acp_session.lock().await = Some(session_id);
                    if !s.cancel.is_cancelled() {
                        *s.state.lock().await = "running".into();
                    }
                }
                DshEvent::TextDelta(text) => s.text.lock().await.push_str(&text),
                DshEvent::Terminal { state, reply } => terminal = Some((state, reply)),
            }
        }
        if let Some(terminal) = terminal {
            break terminal;
        }
    };
    s.cancel.cancel();
    transport.cancel();
    transport.wait_closed().await;
    Ok(if !prompted && terminal.0 == DshState::Unknown {
        (DshState::Failed, String::new())
    } else {
        terminal
    })
}

// unix-only test module: the private ACP peer is a `#!/usr/bin/python3` script
// that must carry the execute bit (`Permissions::from_mode(0o700)`). Windows has
// no POSIX execute bit and an unprivileged Windows process cannot run that
// fixture, so the module is skipped there rather than compiled into a test that
// could never pass.
#[cfg(all(test, unix))]
pub(crate) mod tests {
    use super::*;
    use std::os::unix::fs::PermissionsExt;

    // A private ACP peer, never a real DSH or model process.
    const MOCK: &str = r#"#!/usr/bin/python3
import json,sys,time,os
def send(x): print(json.dumps(x),flush=True)
for line in sys.stdin:
 f=json.loads(line);m=f.get('method');i=f.get('id')
 if m=='initialize':send({'jsonrpc':'2.0','id':i,'result':{'agentCapabilities':{'promptCapabilities':{'image':True}}}})
 elif m=='session/new':send({'jsonrpc':'2.0','id':i,'result':{'sessionId':'acp'}})
 elif m=='session/prompt':
  if os.environ.get('USER')=='cancel':continue
  while not os.path.exists('finish'):time.sleep(.01)
  send({'jsonrpc':'2.0','method':'session/update','params':{'sessionId':'acp','update':{'sessionUpdate':'agent_message_chunk','content':{'type':'text','text':'done'}}}})
  send({'jsonrpc':'2.0','id':i,'result':{'stopReason':'end_turn'}})
 elif m=='session/cancel':send({'jsonrpc':'2.0','id':3,'result':{'stopReason':'cancelled'}})
"#;

    async fn setup(cancel: bool) -> (Arc<DshService>, Value, PathBuf) {
        let root = std::env::temp_dir()
            .canonicalize()
            .unwrap()
            .join(format!("gmgn-dsh-service-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir(&root).unwrap();
        let db = Database::open(root.clone(), None).unwrap();
        let p = fixture(db.clone(), root.clone(), cancel).await;
        (Arc::new(DshService::new(db)), p, root)
    }

    /// Shared private ACP/composition fixture for the actual daemon HTTP tests.
    pub(crate) async fn fixture(db: Database, root: PathBuf, cancel: bool) -> Value {
        let executable = root.join("private-acp");
        std::fs::write(&executable, MOCK).unwrap();
        std::fs::set_permissions(&executable, std::fs::Permissions::from_mode(0o700)).unwrap();
        let mut p = json!({"worldID":"w","residentScope":"s","hostSessionID":"h","runID":"run","eventID":"event","grantToken":uuid::Uuid::new_v4().to_string(),"root":root,"cwd":root,"executable":executable,"entryPoint":root.join("private-entry"),"compositionFile":root.join("composition.yaml"),"attachmentHome":root,"persistenceRoot":root,"persona":"fixture","hostToolsPlugin":root.join("gmgn-host-tools.mjs"),"environment":{"USER":if cancel{"cancel"}else{"fixture"}},"input":"move","tools":[{"name":"move","description":"move","effect":"write","inputSchema":{"type":"object","properties":{"target":{"type":"string"}},"required":["target"]}}]});
        p["arguments"] = json!([p["entryPoint"], "--config", p["compositionFile"]]);
        std::fs::write(root.join("composition.yaml"), composition(&p).unwrap()).unwrap();
        db.call(|store| {
            agent_scheduler::request(&mut store.connection,"agent_loop_configure",&json!({"worldID":"w","residentScope":"s","hostSessionID":"h","hourlyLimit":6,"minimumWakeIntervalSeconds":1}))?;
            store.connection.execute("INSERT INTO agent_loop_events(world,scope,event,payload,state,run,session) VALUES('w','s','event','{}','claimed','run','h')",[]).map_err(|_|"storage_unavailable")?;
            Ok(())
        }).await.unwrap();
        p
    }

    async fn wait(service: &DshService, p: &Value, want: &str) -> Value {
        // 等进展，不等墙钟（原来是 10s 固定上限，并行跑满时会先于被测作业超时）。
        let mut watch =
            crate::test_wait::StallWatch::new("agent_dsh 会话", Duration::from_secs(60));
        loop {
            let read = service.request("agent_dsh_read", p).await.unwrap();
            if read["state"] == want
                || read["pendingTools"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .any(|v| v["phase"] == want)
            {
                return read;
            }
            if !watch.observe(&read) {
                panic!("{}", watch.stalled());
            }
            tokio::time::sleep(Duration::from_millis(10)).await;
        }
    }

    #[tokio::test]
    async fn native_acp_authorize_ledger_receipt_and_real_terminal() {
        let (service, p, root) = setup(false).await;
        service.request("agent_dsh_start", &p).await.unwrap();
        wait(&service, &p, "running").await;
        assert!(!service.accepts_grant("wrong").await);
        let token = p["grantToken"].as_str().unwrap().to_owned();
        assert!(service.accepts_grant(&token).await);
        for extra in ["method", "id", "params", "unexpected"] {
            let mut mixed =
                json!({"v":1,"callId":"invalid","name":"gmgn_move","arguments":{"target":"chair"}});
            mixed[extra] = json!("extra");
            assert_eq!(
                service.host_call(&token, &mixed).await.unwrap_err(),
                "agent_dsh_invalid_request"
            );
        }
        assert_eq!(
            service.host_call(&token, &json!([1, 2])).await.unwrap_err(),
            "agent_dsh_invalid_request"
        );
        let runner = service.clone();
        let private_token = token.clone();
        let call = tokio::spawn(async move {
            runner.host_call(&private_token,&json!({"v":1,"callId":"call","name":"gmgn_move","arguments":{"target":"chair"}})).await
        });
        let read = wait(&service, &p, "authorize").await;
        let mut approval = read["pendingTools"][0].clone();
        approval["decision"] = json!("approved");
        approval["operationID"] = json!("operation");
        let mut wrong = approval.clone();
        wrong["acpSessionID"] = json!("wrong");
        assert_eq!(
            service
                .request("agent_dsh_authorize", &wrong)
                .await
                .unwrap_err(),
            "agent_dsh_receipt_conflict"
        );
        service
            .request("agent_dsh_authorize", &approval)
            .await
            .unwrap();
        assert_eq!(
            service
                .request("agent_dsh_authorize", &approval)
                .await
                .unwrap()["duplicate"],
            true
        );
        let read = wait(&service, &p, "execute").await;
        let mut receipt = read["pendingTools"][0].clone();
        receipt["status"] = json!("completed");
        receipt["output"] = json!({"moved":true});
        let png = base64::engine::general_purpose::STANDARD.encode(b"\x89PNG\r\n\x1a\nfixture");
        receipt["images"] = json!([{"mediaType":"image/png","base64":png}]);
        let mut wrong = receipt.clone();
        wrong["operationID"] = json!("other");
        assert_eq!(
            service
                .request("agent_dsh_tool_receipt", &wrong)
                .await
                .unwrap_err(),
            "agent_dsh_receipt_conflict"
        );
        service
            .request("agent_dsh_tool_receipt", &receipt)
            .await
            .unwrap();
        assert_eq!(
            service
                .request("agent_dsh_tool_receipt", &receipt)
                .await
                .unwrap()["duplicate"],
            true
        );
        let mut conflict = receipt.clone();
        conflict["images"][0]["base64"] =
            json!(base64::engine::general_purpose::STANDARD.encode(b"\x89PNG\r\n\x1a\nchanged"));
        assert_eq!(
            service
                .request("agent_dsh_tool_receipt", &conflict)
                .await
                .unwrap_err(),
            "agent_dsh_receipt_conflict"
        );
        let result = call.await.unwrap().unwrap();
        assert_eq!(result["data"]["moved"], true);
        assert_eq!(result["image"]["base64"], png);
        std::fs::write(root.join("finish"), b"ready").unwrap();
        wait(&service, &p, "completed").await;
        assert!(!service.accepts_grant(&token).await);
        let state = service
            .db
            .call(|store| {
                store
                    .connection
                    .query_row(
                        "SELECT state FROM agent_tool_calls WHERE call='call'",
                        [],
                        |r| r.get::<_, String>(0),
                    )
                    .map_err(|_| "storage_unavailable")
            })
            .await
            .unwrap();
        assert_eq!(state, "finished");
    }

    #[tokio::test]
    async fn approval_cancel_never_dispatches_and_reaps_peer() {
        let (service, p, _root) = setup(true).await;
        service.request("agent_dsh_start", &p).await.unwrap();
        wait(&service, &p, "running").await;
        let runner = service.clone();
        let token = p["grantToken"].as_str().unwrap().to_owned();
        let call = tokio::spawn(async move {
            runner.host_call(&token,&json!({"v":1,"callId":"call","name":"gmgn_move","arguments":{"target":"chair"}})).await
        });
        wait(&service, &p, "authorize").await;
        service.request("agent_dsh_cancel", &p).await.unwrap();
        assert!(call.await.unwrap().is_ok());
        wait(&service, &p, "cancelled").await;
        let count = service
            .db
            .call(|store| {
                store
                    .connection
                    .query_row("SELECT count(*) FROM agent_tool_calls", [], |r| {
                        r.get::<_, i64>(0)
                    })
                    .map_err(|_| "storage_unavailable")
            })
            .await
            .unwrap();
        assert_eq!(count, 0);
    }

    #[tokio::test]
    async fn composition_extra_authority_is_rejected_before_process() {
        let (service, p, root) = setup(false).await;
        let mut extra = p.clone();
        extra["mcpServer"] = json!({"command":"shell"});
        assert_eq!(
            service
                .request("agent_dsh_start", &extra)
                .await
                .unwrap_err(),
            "agent_dsh_unsupported_mcp_configuration"
        );
        let text = std::fs::read_to_string(root.join("composition.yaml"))
            .unwrap()
            .replace("toolBash: false", "toolBash: true");
        std::fs::write(root.join("composition.yaml"), text).unwrap();
        assert!(service.request("agent_dsh_start", &p).await.is_err());
        assert!(
            !service
                .accepts_grant(p["grantToken"].as_str().unwrap())
                .await
        );
    }

    #[tokio::test]
    async fn uncertain_tool_is_not_completed_or_replayed() {
        let (service, p, _root) = setup(true).await;
        service.request("agent_dsh_start", &p).await.unwrap();
        wait(&service, &p, "running").await;
        let runner = service.clone();
        let token = p["grantToken"].as_str().unwrap().to_owned();
        let call = tokio::spawn(async move {
            runner.host_call(&token,&json!({"v":1,"callId":"call","name":"gmgn_move","arguments":{"target":"chair"}})).await
        });
        let read = wait(&service, &p, "authorize").await;
        let mut approval = read["pendingTools"][0].clone();
        approval["decision"] = json!("approved");
        approval["operationID"] = json!("operation");
        service
            .request("agent_dsh_authorize", &approval)
            .await
            .unwrap();
        let read = wait(&service, &p, "execute").await;
        let mut receipt = read["pendingTools"][0].clone();
        receipt["status"] = json!("unknown");
        receipt["output"] = json!({"error":"lost host result"});
        service
            .request("agent_dsh_tool_receipt", &receipt)
            .await
            .unwrap();
        assert_eq!(call.await.unwrap().unwrap()["ok"], false);
        // The *call* is durably unresolved — never guessed into applied/not_applied.
        let state = service
            .db
            .call(|store| {
                store
                    .connection
                    .query_row(
                        "SELECT state FROM agent_tool_calls WHERE call='call'",
                        [],
                        |r| r.get::<_, String>(0),
                    )
                    .map_err(|_| "storage_unavailable")
            })
            .await
            .unwrap();
        assert_eq!(state, "unknown");
        // The *turn* is over, named, and the host — not the daemon — owns its
        // receipt. Before 2026-10-09 the daemon wrote the event `unknown` here,
        // which made this very `agent_loop_complete` fail as
        // `agent_loop_receipt_conflict` (the real log at 16:50:20.659) and left
        // the human-message row dangling in `claimed`.
        //
        // Wait for the session to settle first: `run` finishes the ledger and the
        // session state in that order, and asserting mid-flight would race.
        let mut watch = crate::test_wait::StallWatch::new("agent_dsh 会话终止", Duration::from_secs(60));
        let read = loop {
            let read = service.request("agent_dsh_read", &p).await.unwrap();
            if ["completed", "failed", "cancelled", "unknown"]
                .contains(&read["state"].as_str().unwrap_or_default())
            {
                break read;
            }
            if !watch.observe(&read) {
                panic!("{}", watch.stalled());
            }
            tokio::time::sleep(Duration::from_millis(10)).await;
        };
        assert_eq!(
            read["state"], "failed",
            "`unknown` is what RustDSHSessionClient turns into error 4"
        );
        let event_state = service
            .db
            .call(|store| {
                store
                    .connection
                    .query_row(
                        "SELECT state FROM agent_loop_events WHERE event='event'",
                        [],
                        |r| r.get::<_, String>(0),
                    )
                    .map_err(|_| "storage_unavailable")
            })
            .await
            .unwrap();
        assert_eq!(
            event_state, "claimed",
            "the daemon must not pre-empt the host's own settle"
        );
        let settle = json!({
            "worldID": p["worldID"], "residentScope": p["residentScope"],
            "hostSessionID": p["hostSessionID"], "runID": p["runID"], "eventID": p["eventID"],
            "status": "failed",
            "receipt": {"kind":"resident_model_turn","invocationReturned":true,
                        "executionNotStarted":false,"invocationStarted":true,"outcome":"failed"},
        });
        let accepted = service
            .db
            .call(move |store| {
                crate::agent_scheduler::request(&mut store.connection, "agent_loop_complete", &settle)
            })
            .await
            .unwrap();
        assert_eq!(accepted["accepted"], true);
        assert_eq!(accepted["duplicate"], false);
        // The settled turn is over for good: its event can never be claimed again.
        assert_eq!(
            service.request("agent_dsh_start", &p).await.unwrap_err(),
            "agent_dsh_run_not_claimed"
        );
    }

    /// A call whose owning run already settled can never produce a receipt any
    /// more. Counting it (the rule until 2026-10-09) blocked **every** later
    /// `agent_dsh_start` in the same world+scope with
    /// `agent_dsh_unresolved_tools`, and the DSH path has no caller for
    /// `agent_runtime_reconcile`, so the resident stayed mute for the life of the
    /// database. The record is still kept and still named on stderr — it just
    /// stops gating unrelated turns. A call whose run is still claimed is live
    /// and still refuses.
    #[tokio::test]
    async fn a_stale_unconfirmed_tool_does_not_lock_every_later_start() {
        for (event_state, expected) in [
            ("failed", None),
            ("claimed", Some("agent_dsh_unresolved_tools")),
        ] {
            let (service, p, _root) = setup(false).await;
            let state = event_state.to_owned();
            service
                .db
                .call(move |store| {
                    store
                        .connection
                        .execute(
                            "INSERT INTO agent_loop_events(world,scope,event,payload,state,run,session) VALUES('w','s','old','{}',?1,'oldrun','h')",
                            rusqlite::params![state],
                        )
                        .map_err(|_| "storage_unavailable")?;
                    store
                        .connection
                        .execute(
                            "INSERT INTO agent_tool_calls(world,scope,run,session,call,operation,tool,input,effect,state,receipt) VALUES('w','s','oldrun','h','c-old','op-old','move','{\"target\":\"chair\"}','write','unknown',NULL)",
                            [],
                        )
                        .map_err(|_| "storage_unavailable")?;
                    Ok(())
                })
                .await
                .unwrap();
            match expected {
                None => {
                    assert!(
                        service.request("agent_dsh_start", &p).await.is_ok(),
                        "a settled run's unknown call must not gate a new turn"
                    );
                }
                Some(code) => {
                    assert_eq!(
                        service.request("agent_dsh_start", &p).await.unwrap_err(),
                        code
                    );
                }
            }
        }
    }
    /// A session that ended `unknown` used to be unreplaceable, because only
    /// `completed`/`failed`/`cancelled` were accepted as terminal. `unknown` is
    /// what `run` still writes when its own settle fails, and it is written after
    /// the ACP child was reaped — the session is dead. Refusing to replace it
    /// turned one uncertain turn into a permanent `agent_dsh_session_busy` for the
    /// whole scope.
    #[tokio::test]
    async fn an_unknown_session_is_replaced_instead_of_locking_the_scope() {
        let (service, p, _root) = setup(true).await;
        service.request("agent_dsh_start", &p).await.unwrap();
        wait(&service, &p, "running").await;
        // Put the live session into the one state `run` still writes when its own
        // settle fails, so this test isolates the session gate: no unresolved call
        // is involved at all.
        let session = service.session.lock().await.clone().unwrap();
        *session.state.lock().await = "unknown".into();
        drop(session);
        let calls: i64 = service
            .db
            .call(|store| {
                store
                    .connection
                    .query_row("SELECT count(*) FROM agent_tool_calls", [], |r| r.get(0))
                    .map_err(|_| "storage_unavailable")
            })
            .await
            .unwrap();
        assert_eq!(calls, 0);
        service
            .db
            .call(|store| {
                store
                    .connection
                    .execute(
                        "INSERT INTO agent_loop_events(world,scope,event,payload,state,run,session) VALUES('w','s','event2','{}','claimed','run2','h')",
                        [],
                    )
                    .map_err(|_| "storage_unavailable")?;
                Ok(())
            })
            .await
            .unwrap();
        let mut next = p.clone();
        next["runID"] = json!("run2");
        next["eventID"] = json!("event2");
        next["grantToken"] = json!(uuid::Uuid::new_v4().to_string());
        assert!(
            service.request("agent_dsh_start", &next).await.is_ok(),
            "an unknown session must not be permanently busy"
        );
    }
    /// A refused receipt is not a receipt, but it must not leave the host future
    /// parked on the 120 s transport bound either: nobody can answer it once the
    /// payload was refused. The call still ends `unknown` — never confirmed.
    #[tokio::test]
    async fn a_refused_receipt_settles_the_pending_execution_at_once() {
        let (service, p, _root) = setup(true).await;
        service.request("agent_dsh_start", &p).await.unwrap();
        wait(&service, &p, "running").await;
        let runner = service.clone();
        let token = p["grantToken"].as_str().unwrap().to_owned();
        let call = tokio::spawn(async move {
            runner
                .host_call(
                    &token,
                    &json!({"v":1,"callId":"call","name":"gmgn_move","arguments":{"target":"chair"}}),
                )
                .await
        });
        let read = wait(&service, &p, "authorize").await;
        let mut approval = read["pendingTools"][0].clone();
        approval["decision"] = json!("approved");
        approval["operationID"] = json!("operation");
        service
            .request("agent_dsh_authorize", &approval)
            .await
            .unwrap();
        let read = wait(&service, &p, "execute").await;
        let mut receipt = read["pendingTools"][0].clone();
        receipt["status"] = json!("completed");
        receipt["output"] =
            json!({"padding":"x".repeat(crate::agent_tools::MAXIMUM_RECEIPT_BYTES + 4096)});
        assert_eq!(
            service
                .request("agent_dsh_tool_receipt", &receipt)
                .await
                .unwrap_err(),
            "agent_dsh_invalid_receipt"
        );
        // The executor is released by the refusal itself, not by the 120 s bound:
        // the pending `execute` entry is gone before the receipt call returns.
        let read = service.request("agent_dsh_read", &p).await.unwrap();
        assert!(
            read["pendingTools"]
                .as_array()
                .unwrap()
                .iter()
                .all(|tool| tool["phase"] != "execute"),
            "a refused receipt must release the pending execution at once: {read}"
        );
        assert_eq!(call.await.unwrap().unwrap()["ok"], false);
        let state: String = service
            .db
            .call(|store| {
                store
                    .connection
                    .query_row(
                        "SELECT state FROM agent_tool_calls WHERE call='call'",
                        [],
                        |r| r.get(0),
                    )
                    .map_err(|_| "storage_unavailable")
            })
            .await
            .unwrap();
        assert_eq!(state, "unknown");
    }
    /// The real 2026-10-09 16:50:19.837 shape: the model asked for a motion the
    /// character does not have, the host refused it *by name*
    /// (`[ResidentTool] name=play_motion ok=0 code=motion_unavailable`), and the
    /// whole turn died. A refusal the host reported itself is an **answer**, so it
    /// must settle terminal (`rejected`, host receipt kept), reach the model with
    /// the host's own code, and leave the turn running to try something else.
    #[tokio::test]
    async fn host_reported_refusal_does_not_kill_the_turn() {
        let (service, p, _root) = setup(false).await;
        service.request("agent_dsh_start", &p).await.unwrap();
        wait(&service, &p, "running").await;
        let runner = service.clone();
        let token = p["grantToken"].as_str().unwrap().to_owned();
        let call = tokio::spawn(async move {
            runner.host_call(&token,&json!({"v":1,"callId":"call","name":"gmgn_move","arguments":{"target":"chair"}})).await
        });
        let read = wait(&service, &p, "authorize").await;
        let mut approval = read["pendingTools"][0].clone();
        approval["decision"] = json!("approved");
        approval["operationID"] = json!("operation");
        service
            .request("agent_dsh_authorize", &approval)
            .await
            .unwrap();
        let read = wait(&service, &p, "execute").await;
        let mut receipt = read["pendingTools"][0].clone();
        receipt["status"] = json!("rejected");
        receipt["output"] = json!({
            "ok": false,
            "code": "motion_unavailable",
            "message": "当前角色没有这个动作",
        });
        service
            .request("agent_dsh_tool_receipt", &receipt)
            .await
            .unwrap();
        let answer = call.await.unwrap().unwrap();
        assert_eq!(answer["ok"], false);
        // The host's own answer, not the daemon's generic "宿主工具未能完成".
        assert_eq!(answer["error"]["code"], "motion_unavailable");
        let (state, stored): (String, String) = service
            .db
            .call(|store| {
                store
                    .connection
                    .query_row(
                        "SELECT state,receipt FROM agent_tool_calls WHERE call='call'",
                        [],
                        |r| Ok((r.get(0)?, r.get(1)?)),
                    )
                    .map_err(|_| "storage_unavailable")
            })
            .await
            .unwrap();
        assert_eq!(state, "rejected");
        assert!(stored.contains("motion_unavailable"));
        // The turn was not cancelled: the resident can try another motion now.
        assert_eq!(
            service.request("agent_dsh_read", &p).await.unwrap()["state"],
            "running"
        );
        assert_eq!(
            service.request("agent_dsh_start", &p).await.unwrap_err(),
            "agent_dsh_session_busy"
        );
    }
    /// The live space's `inspect_world` result is **host-owned** data: every enabled
    /// place, every activity with its seat projection, every camera, the motion
    /// catalogue and — while the resident is en route — `movement.waypointIDs`, one id
    /// per waypoint. `marble-living-cabin` (the shipping space, world `84503420-…`)
    /// declares 643 waypoints and the live space held 13 generated props, so the widest
    /// legitimate result crosses the 16 KiB ceiling that exists for the **model's**
    /// arguments. Measured on the real device 2026-10-09 14:50:23, that ceiling refused
    /// the whole receipt as `agent_dsh_invalid_receipt`, left the call `unknown`, and
    /// blocked every later start with `agent_dsh_unresolved_tools`.
    ///
    /// 1000 waypoint ids (~23 KB) is that shape, not padding.
    #[tokio::test]
    async fn host_result_wider_than_one_model_argument_still_settles() {
        let (service, p, _root) = setup(false).await;
        service.request("agent_dsh_start", &p).await.unwrap();
        wait(&service, &p, "running").await;
        let runner = service.clone();
        let token = p["grantToken"].as_str().unwrap().to_owned();
        let call = tokio::spawn(async move {
            runner.host_call(&token,&json!({"v":1,"callId":"call","name":"gmgn_move","arguments":{"target":"chair"}})).await
        });
        let read = wait(&service, &p, "authorize").await;
        let mut approval = read["pendingTools"][0].clone();
        approval["decision"] = json!("approved");
        approval["operationID"] = json!("operation");
        service
            .request("agent_dsh_authorize", &approval)
            .await
            .unwrap();
        let read = wait(&service, &p, "execute").await;
        let mut receipt = read["pendingTools"][0].clone();
        let waypoints: Vec<String> = (0..1000)
            .map(|i| format!("wp.auto.x{}.z{}.h0", i % 26, i / 26))
            .collect();
        receipt["status"] = json!("completed");
        receipt["output"] = json!({"ok":true,"snapshot":{"movement":{"waypointIDs":waypoints}}});
        let encoded = receipt["output"].to_string().len();
        assert!(
            encoded > 16384,
            "the fixture must exceed one model argument: {encoded} bytes"
        );
        assert!(encoded <= crate::agent_tools::MAXIMUM_RECEIPT_BYTES);
        service
            .request("agent_dsh_tool_receipt", &receipt)
            .await
            .unwrap();
        let result = call.await.unwrap().unwrap();
        assert_eq!(result["ok"], true);
        assert_eq!(
            result["data"]["snapshot"]["movement"]["waypointIDs"]
                .as_array()
                .unwrap()
                .len(),
            1000
        );
        // The inner ledger persisted the same wide host result instead of refusing it.
        let (state, stored) = service
            .db
            .call(|store| {
                store
                    .connection
                    .query_row(
                        "SELECT state, length(receipt) FROM agent_tool_calls WHERE call='call'",
                        [],
                        |r| Ok((r.get::<_, String>(0)?, r.get::<_, i64>(1)?)),
                    )
                    .map_err(|_| "storage_unavailable")
            })
            .await
            .unwrap();
        assert_eq!(state, "finished");
        assert!(
            stored > 16384,
            "the ledger keeps the wide receipt: {stored} bytes"
        );
    }

    /// Bounded, not unbounded: a host receipt past its own ceiling is still refused and
    /// never silently completed, and a status outside the host vocabulary is refused
    /// for the same reason.
    #[tokio::test]
    async fn host_result_above_the_receipt_bound_and_unknown_status_are_refused() {
        let (service, p, _root) = setup(false).await;
        service.request("agent_dsh_start", &p).await.unwrap();
        wait(&service, &p, "running").await;
        let runner = service.clone();
        let token = p["grantToken"].as_str().unwrap().to_owned();
        let _call = tokio::spawn(async move {
            runner.host_call(&token,&json!({"v":1,"callId":"call","name":"gmgn_move","arguments":{"target":"chair"}})).await
        });
        let read = wait(&service, &p, "authorize").await;
        let mut approval = read["pendingTools"][0].clone();
        approval["decision"] = json!("approved");
        approval["operationID"] = json!("operation");
        service
            .request("agent_dsh_authorize", &approval)
            .await
            .unwrap();
        let read = wait(&service, &p, "execute").await;
        let mut receipt = read["pendingTools"][0].clone();
        receipt["status"] = json!("completed");
        receipt["output"] = json!({"padding":"x".repeat(crate::agent_tools::MAXIMUM_RECEIPT_BYTES + 4096)});
        // The status vocabulary is checked against a **live** pending execution:
        // once a receipt has been refused, `refuse_receipt` settles that entry in
        // place (it must not park on the 120 s transport bound), so a later call
        // for the same callID can only be `agent_dsh_not_pending`.
        let mut bad_status = receipt.clone();
        bad_status["output"] = json!({"moved":true});
        bad_status["status"] = json!("succeeded");
        assert_eq!(
            service
                .request("agent_dsh_tool_receipt", &bad_status)
                .await
                .unwrap_err(),
            "agent_dsh_invalid_receipt"
        );
        for _ in 0..2 {
            assert_eq!(
                service
                    .request("agent_dsh_tool_receipt", &receipt)
                    .await
                    .unwrap_err(),
                "agent_dsh_invalid_receipt"
            );
        }
        let mut too_many_images = receipt.clone();
        too_many_images["output"] = json!({"moved":true});
        let png = base64::engine::general_purpose::STANDARD.encode(b"\x89PNG\r\n\x1a\nfixture");
        too_many_images["images"] =
            json!([{"mediaType":"image/png","base64":png},{"mediaType":"image/png","base64":png}]);
        assert_eq!(
            service
                .request("agent_dsh_tool_receipt", &too_many_images)
                .await
                .unwrap_err(),
            "agent_dsh_invalid_receipt"
        );
    }
}
