#!/usr/bin/env python3
"""Rejection evidence for `agent_dsh_invalid_tools`: run the real daemon and read its stderr.

    cargo +1.95.0 build --locked -p gmgn-taskd --bin gmgn-taskd
    python3 services/gmgn-taskd/tests/dsh_catalog_probe.py \
        target/debug/gmgn-taskd <catalog.json>

Starts a real `gmgn-taskd` on a scratch root with its stderr captured, claims a real
scheduler event, then sends a real `agent_dsh_start` carrying the caller-supplied tool
catalogue. The daemon's structured rejection line --

    {"event":"rejected","code":...,"tool":...,"path":...,"detail":...}

-- lands in the captured stderr. That is the evidence that was missing on device: the
helper is a child process of the app, so its stderr never reached
`/tmp/app-stderr.log`, and the client only logs the code.

Measured 2026-10-09 with the 52-tool regression fixture in `agent_tools.rs` (elided
descriptions, 15583 bytes) and with the same fixture carrying the shipping
descriptions (25746 bytes), and with the four tools that fixture is missing
(`resize_prop`, `read_resident_state`, `update_resident_intent`,
`capture_space_photo`) added, which is 56 tools / 31574 bytes:

  * before `MAXIMUM_CATALOG_BYTES`: 25746 and 31574 bytes both answer
    `agent_dsh_invalid_tools` with an empty stderr, while 15583 bytes answers
    `{"started": true}` -- the refusal is the shared 16 KiB payload bound, not a schema;
  * after: both register, an oversize catalogue is still refused, and the refusal
    finally says how big the group was.

`catalog.json` is the `tools` array the Swift host would send.
"""

import json
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.request
import uuid

# The exact emitted grammar of ResidentDSHComposition; re-validated by read-back
# before every launch. Same literal as `services/gmgn-taskd/src/agent_dsh.rs`.
COMPOSITION = """# Generated by gmgn ResidentDSHConfiguration; re-validated by read-back before every launch.
- id: llm-deepseek
  name: '@deepseek-ai/dsh-llm-deepseek'
  config:
    reasoningEffort: low
    maxTokens: 8192
    models:
      - id: deepseek-flash
        inputModalities: [text, image]
      - id: deepseek-v4-pro
        inputModalities: [text]
- id: credentials
  name: '@deepseek-ai/dsh-credentials-local'
- id: attachment-local
  name: '@deepseek-ai/dsh-attachment-local'
  config:
    dshHome: '{attachment}'
- id: acp-agent
  name: '@deepseek-ai/dsh-acp-demo'
  config:
    provider: deepseek-official
    model: deepseek-flash
    persistenceRoot: '{persistence}'
    packChunks: false
    persistenceCompression: none
    workspaceContext: false
    toolBash: false
    toolJobs: false
    goals: false
    skills:
      enabled: false
    tools:
      mode: native
    persona: '{persona}'
- id: web
  name: '@deepseek-ai/dsh-web'
  config:
    searchProvider: deepseek-official
- id: web-fetch-http
  name: '@deepseek-ai/dsh-web-fetch-http'
- id: web-search-deepseek
  name: '@deepseek-ai/dsh-web-search-deepseek'
- id: tool-web
  name: '@deepseek-ai/dsh-tool-web'
- id: gmgn-host-tools
  name: '{plugin}'"""


def free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    taskd, catalog_path = sys.argv[1], sys.argv[2]
    tools = json.load(open(catalog_path, encoding="utf-8"))
    tools_bytes = len(json.dumps(tools, separators=(",", ":"), ensure_ascii=False).encode())

    # `--root` must be its own canonical path (`unsafe_path` otherwise); macOS
    # TMPDIR is `/var/...` which canonicalizes to `/private/var/...`.
    root = os.path.realpath(tempfile.mkdtemp(prefix="gmgn-dsh-probe-"))
    os.chmod(root, 0o700)
    entry = os.path.join(root, "private-entry")
    open(entry, "w").close()
    dummy_node = os.path.join(root, "node")
    open(dummy_node, "w").close()
    plugin = os.path.join(root, "gmgn-host-tools.mjs")
    open(plugin, "w").close()
    composition = os.path.join(root, "composition.yaml")
    with open(composition, "w", encoding="utf-8") as handle:
        handle.write(
            COMPOSITION.format(
                attachment=root, persistence=root, persona="probe", plugin=plugin
            )
        )
    endpoint_file = os.path.join(root, "taskd.endpoint.json")
    stderr_path = os.path.join(root, "taskd.stderr.log")

    with open(stderr_path, "wb") as stderr:
        daemon = subprocess.Popen(
            [
                taskd,
                "--root",
                root,
                "--endpoint-file",
                endpoint_file,
                "--concurrency",
                "2",
            ],
            stdout=subprocess.DEVNULL,
            stderr=stderr,
        )
    try:
        endpoint = None
        for _ in range(200):
            if os.path.exists(endpoint_file):
                try:
                    endpoint = json.load(open(endpoint_file, encoding="utf-8"))
                    break
                except json.JSONDecodeError:
                    pass
            time.sleep(0.05)
        if endpoint is None:
            print("daemon never published an endpoint")
            print(open(stderr_path, encoding="utf-8", errors="replace").read())
            return 1

        counter = [0]

        def rpc(method, **extra):
            counter[0] += 1
            payload = {
                "worldID": "w",
                "residentScope": "s",
                "hostSessionID": "h",
                **extra,
            }
            body = json.dumps(
                {"id": "probe-%d" % counter[0], "method": method, "params": payload}
            ).encode()
            request = urllib.request.Request(
                "http://%s/rpc" % endpoint["address"],
                data=body,
                headers={
                    "Authorization": "Bearer %s" % endpoint["token"],
                    "Content-Type": "application/json",
                },
            )
            return json.loads(urllib.request.urlopen(request, timeout=30).read())

        # A real DSH turn only starts on an event the scheduler has claimed; the
        # authority refuses anything else with `agent_dsh_run_not_claimed` before
        # registration is ever consulted.
        rpc(
            "agent_loop_configure",
            hostSessionID="h",
            hourlyLimit=6,
            minimumWakeIntervalSeconds=1,
            backgroundEnabled=True,
            available=True,
        )
        rpc(
            "agent_loop_enqueue",
            eventID="e",
            intentID="i",
            kind="continuation",
            intentState="active",
            command={"observe": True},
        )
        claim = rpc(
            "agent_loop_claim",
            runID="r",
            hostSessionID="h",
            nowMillis=int(time.time() * 1000),
        )
        if not claim.get("result", {}).get("claimed"):
            print("scheduler refused the probe claim: %s" % json.dumps(claim))
            return 1

        params = {
            "worldID": "w",
            "residentScope": "s",
            "hostSessionID": "h",
            "runID": "r",
            "eventID": "e",
            "grantToken": str(uuid.uuid4()),
            "root": root,
            "cwd": root,
            "executable": dummy_node,
            "entryPoint": entry,
            "compositionFile": composition,
            "attachmentHome": root,
            "persistenceRoot": root,
            "persona": "probe",
            "hostToolsPlugin": plugin,
            "environment": {"HOME": root, "TMPDIR": root},
            "arguments": [entry, "--config", composition],
            "input": "probe",
            "tools": tools,
        }
        body = json.dumps(
            {"id": "probe", "method": "agent_dsh_start", "params": params}
        ).encode()
        request = urllib.request.Request(
            "http://%s/rpc" % endpoint["address"],
            data=body,
            headers={
                "Authorization": "Bearer %s" % endpoint["token"],
                "Content-Type": "application/json",
            },
        )
        reply = json.loads(urllib.request.urlopen(request, timeout=30).read())
        print("catalog: %d tools, %d bytes" % (len(tools), tools_bytes))
        print("reply: %s" % json.dumps(reply, ensure_ascii=False))
        time.sleep(0.3)
        print("--- daemon stderr ---")
        print(open(stderr_path, encoding="utf-8", errors="replace").read().strip() or "(empty)")
        return 0
    finally:
        daemon.terminate()
        try:
            daemon.wait(timeout=5)
        except subprocess.TimeoutExpired:
            daemon.kill()
        shutil.rmtree(root, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
